server {
    listen 80;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    
    # Tell Nginx to look inside Laravel's public directory
    root /app/public;

    # Handle standard URLs and pass them to index.php if the file doesn't exist
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # The Magic Link: Send PHP files to your PHP-FPM container
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        # '9MintApp_Container' matches the container_name in your compose file!
        fastcgi_pass 9MintApp_Container:9000; 
        
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}

server {
       listen 443 ssl;
       server_name localhost;

       ssl_certificate     /etc/nginx/certs/localhost.crt;
       ssl_certificate_key /etc/nginx/certs/localhost.key;

       root /app/public;
      
       # Handle standard URLs and pass them to index.php if the file doesn't exist
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # The Magic Link: Send PHP files to your PHP-FPM container
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        # '9MintApp_Container' matches the container_name in your compose file!
        fastcgi_pass 9MintApp_Container:9000; 
        
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
   }
}